#for plotting
fig = plt.figure()
ax = fig.add_subplot(111)
plt.plot(ts,1000*(np.array(x_sol)-x_swc),color="blue", linewidth=1.5)
plt.scatter(ts,1000*(np.array(x_sol)-x_swc),color="blue",marker="o",s=4)
plt.title("X position error of the predicted orbit \n",fontsize=14)
plt.xlabel('time [s]')
plt.ylabel('X error [m]')
plt.grid(b=True, which='major', color='grey', linestyle='-', alpha=0.3)
plt.minorticks_on()
plt.grid(b=True, which='minor', color='grey', linestyle='-', alpha=0.1)
plt.show()

fig = plt.figure()
ax = fig.add_subplot(111)
plt.plot(ts,1000*(np.array(y_sol)-y_swc),color="red", linewidth=1.5)
plt.scatter(ts,1000*(np.array(y_sol)-y_swc),color="red",marker="o",s=4)
plt.title("Y position error of the predicted orbit \n",fontsize=14)
plt.xlabel('time [s]')
plt.ylabel('Y error [m]')
plt.grid(b=True, which='major', color='grey', linestyle='-', alpha=0.3)
plt.minorticks_on()
plt.grid(b=True, which='minor', color='grey', linestyle='-', alpha=0.1)
plt.show()